In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

In [7]:
df=pd.read_excel("flight_price.xlsx")
df

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302
...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [8]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  object
 1   Date_of_Journey  10683 non-null  object
 2   Source           10683 non-null  object
 3   Destination      10683 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10683 non-null  object
 6   Arrival_Time     10683 non-null  object
 7   Duration         10683 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10683 non-null  object
 10  Price            10683 non-null  int64
dtypes: int64(1), object(10)
memory usage: 918.2+ KB

In [10]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [11]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [13]:
df.sample(5)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9179,Air India,6/06/2019,Mumbai,Hyderabad,BOM → HYD,13:55,15:25,1h 30m,non-stop,No info,3625
1918,Jet Airways,01/03/2019,Banglore,New Delhi,BLR → BOM → DEL,16:55,08:15 02 Mar,15h 20m,1 stop,No info,26890
1850,Air India,24/06/2019,Delhi,Cochin,DEL → CCU → BOM → COK,14:25,19:15 25 Jun,28h 50m,2 stops,No info,13381
9896,Multiple carriers,27/05/2019,Delhi,Cochin,DEL → BOM → COK,09:00,21:00,12h,1 stop,In-flight meal not included,7886
6596,Jet Airways,12/06/2019,Kolkata,Banglore,CCU → BOM → BLR,08:25,16:20,7h 55m,1 stop,In-flight meal not included,9899

In [14]:
df.shape

(10683, 11)

In [15]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              1
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        1
Additional_Info    0
Price              0
dtype: int64

In [17]:
df.dropna(axis=0,inplace=True)

In [16]:
df['Total_Stops'].unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops'],
      dtype=object)

In [18]:
df.isnull().sum()

Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

In [19]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price'],
      dtype='object')

In [23]:
df['day']=df['Date_of_Journey'].str.split('/').str[0]  
df['month']=df['Date_of_Journey'].str.split('/').str[1]
df['year']=df['Date_of_Journey'].str.split('/').str[2]

In [24]:
df['month']

0        03
1        05
2        06
3        05
4        03
         ..
10678    04
10679    04
10680    04
10681    03
10682    05
Name: month, Length: 10682, dtype: object

In [25]:
df.columns

Index(['Airline', 'Date_of_Journey', 'Source', 'Destination', 'Route',
       'Dep_Time', 'Arrival_Time', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'day', 'month', 'year'],
      dtype='object')

In [26]:
df['day']=df['day'].astype(int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
 11  day              10682 non-null  int64
 12  month            10682 non-null  object
 13  year             10682 non-null  object
dtypes: int64(2), object(12)
memory usage: 1.5+ MB

In [28]:
df['month']=df['month'].astype(int)
df['year']=df['year'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Date_of_Journey  10682 non-null  object
 2   Source           10682 non-null  object
 3   Destination      10682 non-null  object
 4   Route            10682 non-null  object
 5   Dep_Time         10682 non-null  object
 6   Arrival_Time     10682 non-null  object
 7   Duration         10682 non-null  object
 8   Total_Stops      10682 non-null  object
 9   Additional_Info  10682 non-null  object
 10  Price            10682 non-null  int64
 11  day              10682 non-null  int64
 12  month            10682 non-null  int64
 13  year             10682 non-null  int64
dtypes: int64(4), object(10)
memory usage: 1.5+ MB

In [29]:
df.drop('Date_of_Journey',axis=1,inplace=True)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Dep_Time         10682 non-null  object
 5   Arrival_Time     10682 non-null  object
 6   Duration         10682 non-null  object
 7   Total_Stops      10682 non-null  object
 8   Additional_Info  10682 non-null  object
 9   Price            10682 non-null  int64
 10  day              10682 non-null  int64
 11  month            10682 non-null  int64
 12  year             10682 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1.4+ MB

In [35]:
df.Arrival_Time.apply(lambda x: x.split(' '))

0        [01:10, 22, Mar]
1                 [13:15]
2        [04:25, 10, Jun]
3                 [23:30]
4                 [21:35]
               ...
10678             [22:25]
10679             [23:20]
10680             [11:20]
10681             [14:10]
10682             [19:15]
Name: Arrival_Time, Length: 10682, dtype: object

In [39]:
#i want only the time that is zeroth element.
df['Arrival_Time']=df.Arrival_Time.apply(lambda x:x.split(' ')[0])

In [43]:
df['arrival_hour']=df['Arrival_Time'].str.split(':').str[0]

In [44]:
df['arrival_hour']

0        01
1        13
2        04
3        23
4        21
         ..
10678    22
10679    23
10680    11
10681    14
10682    19
Name: arrival_hour, Length: 10682, dtype: object

In [46]:
df['arrival_minute']=df['Arrival_Time'].str.split(":").str[1]
df['arrival_minute']

0        10
1        15
2        25
3        30
4        35
         ..
10678    25
10679    20
10680    20
10681    10
10682    15
Name: arrival_minute, Length: 10682, dtype: object

In [48]:
df.drop("Arrival_Time",axis=1,inplace=True)

In [49]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'day', 'month', 'year',
       'arrival_hour', 'arrival_minute'],
      dtype='object')

In [50]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
day                 int64
month               int64
year                int64
arrival_hour       object
arrival_minute     object
dtype: object

In [51]:
df['arrival_hour']=df['arrival_hour'].astype(int)

In [52]:
df['arrival_minute']=df['arrival_minute'].astype(int)

In [53]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
day                 int64
month               int64
year                int64
arrival_hour        int64
arrival_minute      int64
dtype: object

In [54]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'day', 'month', 'year',
       'arrival_hour', 'arrival_minute'],
      dtype='object')

In [56]:
df['Dep_Time']

0        22:20
1        05:50
2        09:25
3        18:05
4        16:50
         ...
10678    19:55
10679    20:45
10680    08:20
10681    11:30
10682    10:55
Name: Dep_Time, Length: 10682, dtype: object

In [57]:
df['dep_hour']=df['Dep_Time'].str.split(':').str[0]

In [59]:
df['dep_minute']=df['Dep_Time'].str.split(":").str[1]

In [61]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Dep_Time', 'Duration',
       'Total_Stops', 'Additional_Info', 'Price', 'day', 'month', 'year',
       'arrival_hour', 'arrival_minute', 'dep_hour', 'dep_minute'],
      dtype='object')

In [62]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Dep_Time           object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
day                 int64
month               int64
year                int64
arrival_hour        int64
arrival_minute      int64
dep_hour           object
dep_minute         object
dtype: object

In [65]:
df.drop('Dep_Time',axis=1,inplace=True)

In [66]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Route', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'day', 'month', 'year', 'arrival_hour',
       'arrival_minute', 'dep_hour', 'dep_minute'],
      dtype='object')

In [67]:
df['dep_hour']=df['dep_hour'].astype(int)

In [68]:
df['dep_minute']=df['dep_minute'].astype(int)

In [69]:
df.dtypes

Airline            object
Source             object
Destination        object
Route              object
Duration           object
Total_Stops        object
Additional_Info    object
Price               int64
day                 int64
month               int64
year                int64
arrival_hour        int64
arrival_minute      int64
dep_hour            int64
dep_minute          int64
dtype: object

In [71]:
df.Total_Stops .unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [73]:
df.Total_Stops.isna().sum()

np.int64(0)

In [75]:
df[df['Total_Stops'].isnull()]

Empty DataFrame
Columns: [Airline, Source, Destination, Route, Duration, Total_Stops, Additional_Info, Price, day, month, year, arrival_hour, arrival_minute, dep_hour, dep_minute]
Index: []

In [76]:
df['Total_Stops'].mode()

0    1 stop
Name: Total_Stops, dtype: object

In [77]:
df.Total_Stops .unique()

array(['non-stop', '2 stops', '1 stop', '3 stops', '4 stops'],
      dtype=object)

In [83]:
df['total_stops']=df['Total_Stops'].map({"non-stop":0 ,"1 stop":1,"2 stops":2,"3 stops":3,"4 stops":4})

In [86]:
df['total_stops'].unique()

array([0, 2, 1, 3, 4])

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Route            10682 non-null  object
 4   Duration         10682 non-null  object
 5   Total_Stops      10682 non-null  object
 6   Additional_Info  10682 non-null  object
 7   Price            10682 non-null  int64
 8   day              10682 non-null  int64
 9   month            10682 non-null  int64
 10  year             10682 non-null  int64
 11  arrival_hour     10682 non-null  int64
 12  arrival_minute   10682 non-null  int64
 13  dep_hour         10682 non-null  int64
 14  dep_minute       10682 non-null  int64
 15  total_stops      10682 non-null  int64
dtypes: int64(9), object(7)
memory usage: 1.6+ MB

In [88]:
df['Route']

0                    BLR → DEL
1        CCU → IXR → BBI → BLR
2        DEL → LKO → BOM → COK
3              CCU → NAG → BLR
4              BLR → NAG → DEL
                 ...
10678                CCU → BLR
10679                CCU → BLR
10680                BLR → DEL
10681                BLR → DEL
10682    DEL → GOI → BOM → COK
Name: Route, Length: 10682, dtype: object

In [92]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Duration', 'Total_Stops',
       'Additional_Info', 'Price', 'day', 'month', 'year', 'arrival_hour',
       'arrival_minute', 'dep_hour', 'dep_minute', 'total_stops'],
      dtype='object')

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Duration         10682 non-null  object
 4   Total_Stops      10682 non-null  object
 5   Additional_Info  10682 non-null  object
 6   Price            10682 non-null  int64
 7   day              10682 non-null  int64
 8   month            10682 non-null  int64
 9   year             10682 non-null  int64
 10  arrival_hour     10682 non-null  int64
 11  arrival_minute   10682 non-null  int64
 12  dep_hour         10682 non-null  int64
 13  dep_minute       10682 non-null  int64
 14  total_stops      10682 non-null  int64
dtypes: int64(9), object(6)
memory usage: 1.6+ MB

In [95]:
df.Duration

0        2h 50m
1        7h 25m
2           19h
3        5h 25m
4        4h 45m
          ...
10678    2h 30m
10679    2h 35m
10680        3h
10681    2h 40m
10682    8h 20m
Name: Duration, Length: 10682, dtype: object

In [103]:
df['duration_hour']=df.Duration.str.split(" ").str[0].str.split('h').str[0]

In [104]:
df['duration_hour']

0         2
1         7
2        19
3         5
4         4
         ..
10678     2
10679     2
10680     3
10681     2
10682     8
Name: duration_hour, Length: 10682, dtype: object

In [105]:
df['duration_minute']=df.Duration.str.split(" ").str[1].str.split('m').str[1]
df['duration_minute']

0
1
2        NaN
3
4
        ...
10678
10679
10680    NaN
10681
10682
Name: duration_minute, Length: 10682, dtype: object

In [106]:
df.drop('Duration',axis=1,inplace=True)

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Total_Stops      10682 non-null  object
 4   Additional_Info  10682 non-null  object
 5   Price            10682 non-null  int64
 6   day              10682 non-null  int64
 7   month            10682 non-null  int64
 8   year             10682 non-null  int64
 9   arrival_hour     10682 non-null  int64
 10  arrival_minute   10682 non-null  int64
 11  dep_hour         10682 non-null  int64
 12  dep_minute       10682 non-null  int64
 13  total_stops      10682 non-null  int64
 14  duration_hour    10682 non-null  object
 15  duration_minute  9650 non-null   object
dtypes: int64(9), object(7)
memory usage: 1.6+ MB

In [109]:
df['duration_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '5m', '41', '40'], dtype=object)

In [112]:
df['duration_hour']=df['duration_hour'].str.replace("5m","5")

In [113]:
df['duration_hour'].unique()

array(['2', '7', '19', '5', '4', '15', '21', '25', '13', '12', '26', '22',
       '23', '20', '10', '6', '11', '8', '16', '3', '27', '1', '14', '9',
       '18', '17', '24', '30', '28', '29', '37', '34', '38', '35', '36',
       '47', '33', '32', '31', '42', '39', '41', '40'], dtype=object)

In [115]:
df['duration_hour']=df['duration_hour'].astype(int)

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10682 entries, 0 to 10682
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10682 non-null  object
 1   Source           10682 non-null  object
 2   Destination      10682 non-null  object
 3   Total_Stops      10682 non-null  object
 4   Additional_Info  10682 non-null  object
 5   Price            10682 non-null  int64
 6   day              10682 non-null  int64
 7   month            10682 non-null  int64
 8   year             10682 non-null  int64
 9   arrival_hour     10682 non-null  int64
 10  arrival_minute   10682 non-null  int64
 11  dep_hour         10682 non-null  int64
 12  dep_minute       10682 non-null  int64
 13  total_stops      10682 non-null  int64
 14  duration_hour    10682 non-null  int64
 15  duration_minute  9650 non-null   object
dtypes: int64(10), object(6)
memory usage: 1.6+ MB

In [120]:
df['Additional_Info'].unique()

array(['No info', 'In-flight meal not included',
       'No check-in baggage included', '1 Short layover', 'No Info',
       '1 Long layover', 'Change airports', 'Business class',
       'Red-eye flight', '2 Long layover'], dtype=object)

In [122]:
df[['Airline','Source','Destination','Additional_Info']]

           Airline    Source Destination Additional_Info
0           IndiGo  Banglore   New Delhi         No info
1        Air India   Kolkata    Banglore         No info
2      Jet Airways     Delhi      Cochin         No info
3           IndiGo   Kolkata    Banglore         No info
4           IndiGo  Banglore   New Delhi         No info
...            ...       ...         ...             ...
10678     Air Asia   Kolkata    Banglore         No info
10679    Air India   Kolkata    Banglore         No info
10680  Jet Airways  Banglore       Delhi         No info
10681      Vistara  Banglore   New Delhi         No info
10682    Air India     Delhi      Cochin         No info

[10682 rows x 4 columns]

In [123]:
df.Additional_Info.value_counts()

Additional_Info
No info                         8344
In-flight meal not included     1982
No check-in baggage included     320
1 Long layover                    19
Change airports                    7
Business class                     4
No Info                            3
1 Short layover                    1
Red-eye flight                     1
2 Long layover                     1
Name: count, dtype: int64

In [124]:
#all of the above data is categorical data so we will be using one hot enconding

In [125]:
from sklearn.preprocessing import OneHotEncoder

In [126]:
encoder=OneHotEncoder()

In [127]:
encoder

OneHotEncoder()

In [130]:
encoded_data=encoder.fit_transform(df[['Airline','Source','Destination','Additional_Info']]).toarray()

In [129]:
encoder.get_feature_names_out()

array(['Airline_Air Asia', 'Airline_Air India', 'Airline_GoAir',
       'Airline_IndiGo', 'Airline_Jet Airways',
       'Airline_Jet Airways Business', 'Airline_Multiple carriers',
       'Airline_Multiple carriers Premium economy', 'Airline_SpiceJet',
       'Airline_Trujet', 'Airline_Vistara',
       'Airline_Vistara Premium economy', 'Source_Banglore',
       'Source_Chennai', 'Source_Delhi', 'Source_Kolkata',
       'Source_Mumbai', 'Destination_Banglore', 'Destination_Cochin',
       'Destination_Delhi', 'Destination_Hyderabad',
       'Destination_Kolkata', 'Destination_New Delhi',
       'Additional_Info_1 Long layover',
       'Additional_Info_1 Short layover',
       'Additional_Info_2 Long layover', 'Additional_Info_Business class',
       'Additional_Info_Change airports',
       'Additional_Info_In-flight meal not included',
       'Additional_Info_No Info',
       'Additional_Info_No check-in baggage included',
       'Additional_Info_No info', 'Additional_Info_Red-eye flight'],
      dtype=object)

In [139]:
encoded_df=pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out())

In [132]:
df.columns

Index(['Airline', 'Source', 'Destination', 'Total_Stops', 'Additional_Info',
       'Price', 'day', 'month', 'year', 'arrival_hour', 'arrival_minute',
       'dep_hour', 'dep_minute', 'total_stops', 'duration_hour',
       'duration_minute'],
      dtype='object')

In [136]:
df.drop(['Airline','Source','Destination','Additional_Info'],axis=1,inplace=True)

In [137]:
df.columns

Index(['Total_Stops', 'Price', 'day', 'month', 'year', 'arrival_hour',
       'arrival_minute', 'dep_hour', 'dep_minute', 'total_stops',
       'duration_hour', 'duration_minute'],
      dtype='object')

In [140]:
encoded_df

,Airline_Air Asia,Airline_Air India,Airline_GoAir,Airline_IndiGo,Airline_Jet Airways,Airline_Jet Airways Business,Airline_Multiple carriers,Airline_Multiple carriers Premium economy,Airline_SpiceJet,Airline_Trujet,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10677,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10678,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10679,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [145]:
final_df=pd.concat([df,encoded_df],axis=1)

In [146]:
final_df

,Total_Stops,Price,day,month,year,arrival_hour,arrival_minute,dep_hour,dep_minute,total_stops,...,Additional_Info_1 Long layover,Additional_Info_1 Short layover,Additional_Info_2 Long layover,Additional_Info_Business class,Additional_Info_Change airports,Additional_Info_In-flight meal not included,Additional_Info_No Info,Additional_Info_No check-in baggage included,Additional_Info_No info,Additional_Info_Red-eye flight
0,non-stop,3897.0,24.0,3.0,2019.0,1.0,10.0,22.0,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,2 stops,7662.0,1.0,5.0,2019.0,13.0,15.0,5.0,50.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2 stops,13882.0,9.0,6.0,2019.0,4.0,25.0,9.0,25.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1 stop,6218.0,12.0,5.0,2019.0,23.0,30.0,18.0,5.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1 stop,13302.0,1.0,3.0,2019.0,21.0,35.0,16.0,50.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10679,non-stop,4145.0,27.0,4.0,2019.0,23.0,20.0,20.0,45.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10680,non-stop,7229.0,27.0,4.0,2019.0,11.0,20.0,8.0,20.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10681,non-stop,12648.0,1.0,3.0,2019.0,14.0,10.0,11.0,30.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
10682,2 stops,11753.0,9.0,5.0,2019.0,19.0,15.0,10.0,55.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [147]:
final_df.dtypes

Total_Stops                                      object
Price                                           float64
day                                             float64
month                                           float64
year                                            float64
arrival_hour                                    float64
arrival_minute                                  float64
dep_hour                                        float64
dep_minute                                      float64
total_stops                                     float64
duration_hour                                   float64
duration_minute                                  object
Airline_Air Asia                                float64
Airline_Air India                               float64
Airline_GoAir                                   float64
Airline_IndiGo                                  float64
Airline_Jet Airways                             float64
Airline_Jet Airways Business                    float64
Airline_Multiple carriers                       float64
Airline_Multiple carriers Premium economy       float64
Airline_SpiceJet                                float64
Airline_Trujet                                  float64
Airline_Vistara                                 float64
Airline_Vistara Premium economy                 float64
Source_Banglore                                 float64
Source_Chennai                                  float64
Source_Delhi                                    float64
Source_Kolkata                                  float64
Source_Mumbai                                   float64
Destination_Banglore                            float64
Destination_Cochin                              float64
Destination_Delhi                               float64
Destination_Hyderabad                           float64
Destination_Kolkata                             float64
Destination_New Delhi                           float64
Additional_Info_1 Long layover                  float64
Additional_Info_1 Short layover                 float64
Additional_Info_2 Long layover                  float64
Additional_Info_Business class                  float64
Additional_Info_Change airports                 float64
Additional_Info_In-flight meal not included     float64
Additional_Info_No Info                         float64
Additional_Info_No check-in baggage included    float64
Additional_Info_No info                         float64
Additional_Info_Red-eye flight                  float64
dtype: object