Question 1 : Explain the fundamental differences between DDL, DML, and DQL commands in SQL. Provide one example for each type of command.

  - DDL (Data Definition Language):
      - Used to define, modify, and delete database structures such as tables, schemas, and indexes.

      - Common commands: CREATE, ALTER, DROP, TRUNCATE

  - DML (Data Manipulation Language):
      - Used to insert, update, and delete data in tables.

     - Common commands: INSERT, UPDATE, DELETE

  - DQL (Data Query Language):
      - Used to retrieve data from database tables.

      - Common command: SELECT

  - Difference Summary:
    - DDL defines structure | DML manipulates data | DQL retrieves data.

In [ ]:


DROP TABLE IF EXISTS Students;

CREATE TABLE Students (
    ID INT,
    Name VARCHAR(50)
);

INSERT INTO Students VALUES (1, 'Riya');
INSERT INTO Students VALUES (2, 'Amit');
INSERT INTO Students VALUES (3, 'Neha');

SELECT * FROM Students;

In [12]:
import sqlite3
import pandas as pd

# Create / Connect database
conn = sqlite3.connect('student.db')
cursor = conn.cursor()
cursor.execute("""
DROP TABLE IF EXISTS Students;
""")

cursor.execute("""
CREATE TABLE Students (
    ID INT,
    Name VARCHAR(50)
);
""")

conn.commit()
cursor.execute("INSERT INTO Students VALUES (1, 'Riya')")
cursor.execute("INSERT INTO Students VALUES (2, 'Amit')")
cursor.execute("INSERT INTO Students VALUES (3, 'Neha')")

conn.commit()
query = "SELECT * FROM Students;"
df = pd.read_sql(query, conn)
df

   ID  Name
0   1  Riya
1   2  Amit
2   3  Neha

Question 2 : What is the purpose of SQL constraints? Name and describe three common types of constraints, providing a simple scenario where each would be useful.

  - Purpose of SQL Constraints:
      - Constraints ensure data integrity, accuracy, and reliability in a database.

  - 1. PRIMARY KEY Constraint:

  - Ensures unique identification of each record.

  - Example: StudentID as primary key to avoid duplicate entries
  - 2. FOREIGN KEY Constraint:

  - Maintains relationship between two tables.

  - Example: CustomerID in Orders referencing Customers table.
  - 3. NOT NULL Constraint:

  - Prevents empty values.

  - Example: Name column must always have data.

In [ ]:
StudentID INT PRIMARY KEY
CustomerID INT FOREIGN KEY REFERENCES Customers(CustomerID)
Name VARCHAR(50) NOT NULL

In [15]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('college.db')
cursor = conn.cursor()
cursor.execute("""
DROP TABLE IF EXISTS Customers;
""")

cursor.execute("""
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(50)
);
""")

conn.commit()
cursor.execute("INSERT INTO Customers VALUES (1, 'Riya')")
cursor.execute("INSERT INTO Customers VALUES (2, 'Amit')")
cursor.execute("INSERT INTO Customers VALUES (3, 'Neha')")

conn.commit()
cursor.execute("""
DROP TABLE IF EXISTS Students;
""")

cursor.execute("""
CREATE TABLE Students (
    StudentID INT PRIMARY KEY,
    CustomerID INT,
    Name VARCHAR(50) NOT NULL,
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
""")

conn.commit()
cursor.execute("INSERT INTO Students VALUES (101, 1, 'Riya Student')")
cursor.execute("INSERT INTO Students VALUES (102, 2, 'Amit Student')")
cursor.execute("INSERT INTO Students VALUES (103, 3, 'Neha Student')")

conn.commit()
pd.read_sql("SELECT * FROM Students", conn)

   StudentID  CustomerID          Name
0        101           1  Riya Student
1        102           2  Amit Student
2        103           3  Neha Student

Question 3 : Explain the difference between LIMIT and OFFSET clauses in SQL. How would you use them together to retrieve the third page of results, assuming each page has 10 records?

  - LIMIT:
     - Restricts the number of rows returned.

  - OFFSET:
    - Skips a specified number of rows before returning results.

     - Retrieve 3rd Page (10 records per page):
    - Skip first 20 records → display next 10 records.

  - Explanation:

  - Page 1 → OFFSET 0

  - Page 2 → OFFSET 10

  - Page 3 → OFFSET 20

In [ ]:
SELECT * FROM Products
LIMIT 10 OFFSET 20;

In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('shop.db')
cursor = conn.cursor()
cursor.execute("""
DROP TABLE IF EXISTS Products;
""")

cursor.execute("""
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(50),
    Price INT
);
""")

conn.commit()
for i in range(1, 31):
    cursor.execute("INSERT INTO Products VALUES (?, ?, ?)",
                   (i, f'Product_{i}', i * 10))

conn.commit()
query = """
SELECT * FROM Products
LIMIT 10 OFFSET 20;
"""
pd.read_sql(query, conn)

   ProductID ProductName  Price
0         21  Product_21    210
1         22  Product_22    220
2         23  Product_23    230
3         24  Product_24    240
4         25  Product_25    250
5         26  Product_26    260
6         27  Product_27    270
7         28  Product_28    280
8         29  Product_29    290
9         30  Product_30    300

Question 4 : What is a Common Table Expression (CTE) in SQL, and what are its main benefits? Provide a simple SQL example demonstrating its usage.

  - CTE (Common Table Expression):
     - A temporary named result set used inside a SQL query to improve readability and structure.

  - Benefits:

    - Improves query readability

   - Simplifies complex joins

    - Enables recursion

   - Easy debugging

In [17]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('shop.db')
cursor = conn.cursor()
cursor.execute("""
DROP TABLE IF EXISTS Products;
""")

cursor.execute("""
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(50),
    Price INT
);
""")

conn.commit()
query = """
WITH HighPriceProducts AS (
    SELECT ProductName, Price
    FROM Products
    WHERE Price > 100
)
SELECT * FROM HighPriceProducts;
"""

pd.read_sql(query, conn)
for i in range(1, 21):
    cursor.execute("INSERT INTO Products VALUES (?, ?, ?)",
                   (i, f'Product_{i}', i * 20))

conn.commit()
query = """
WITH HighPriceProducts AS (
    SELECT ProductName, Price
    FROM Products
    WHERE Price > 100
)
SELECT * FROM HighPriceProducts;
"""

pd.read_sql(query, conn)

   ProductName  Price
0    Product_6    120
1    Product_7    140
2    Product_8    160
3    Product_9    180
4   Product_10    200
5   Product_11    220
6   Product_12    240
7   Product_13    260
8   Product_14    280
9   Product_15    300
10  Product_16    320
11  Product_17    340
12  Product_18    360
13  Product_19    380
14  Product_20    400

Question 5 : Describe the concept of SQL Normalization and its primary goals. Briefly explain the first three normal forms (1NF, 2NF, 3NF).

  - SQL Normalization:
     - Process of organizing data to reduce redundancy and improve integrity.

  - Primary Goals:

    - Eliminate data duplication

    - Ensure consistency

    - Simplify maintenance

  - 1NF (First Normal Form):

    - No repeating groups

    - Atomic values only

  - 2NF (Second Normal Form):

    - Must be in 1NF

    - No partial dependency

  - 3NF (Third Normal Form):

    - Must be in 2NF

    - No transitive dependency

Question 6 : Create a database named ECommerceDB and perform the following tasks:

In [18]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ECommerceDB.db')
cursor = conn.cursor()

# Enable foreign key constraint
cursor.execute("PRAGMA foreign_keys = ON;")
cursor.execute("""
DROP TABLE IF EXISTS Categories;
""")

cursor.execute("""
CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL UNIQUE
);
""")

conn.commit()
cursor.execute("""
DROP TABLE IF EXISTS Products;
""")

cursor.execute("""
CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL UNIQUE,
    CategoryID INT,
    Price DECIMAL(10,2) NOT NULL,
    StockQuantity INT,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);
""")

conn.commit()
cursor.execute("""
DROP TABLE IF EXISTS Customers;
""")

cursor.execute("""
CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    JoinDate DATE
);
""")

conn.commit()
cursor.execute("""
DROP TABLE IF EXISTS Orders;
""")

cursor.execute("""
CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    OrderDate DATE NOT NULL,
    TotalAmount DECIMAL(10,2),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
""")

conn.commit()
cursor.executemany("""
INSERT INTO Categories VALUES (?, ?)
""", [
    (1, 'Electronics'),
    (2, 'Clothing'),
    (3, 'Books')
])

conn.commit()
cursor.executemany("""
INSERT INTO Products VALUES (?, ?, ?, ?, ?)
""", [
    (101, 'Mobile Phone', 1, 15000.00, 50),
    (102, 'Laptop', 1, 55000.00, 20),
    (103, 'T-Shirt', 2, 500.00, 100),
    (104, 'Python Book', 3, 700.00, 40)
])

conn.commit()
cursor.executemany("""
INSERT INTO Customers VALUES (?, ?, ?, ?)
""", [
    (1, 'Ruchi', 'ruchi@gmail.com', '2024-01-10'),
    (2, 'Amit', 'amit@gmail.com', '2024-02-15'),
    (3, 'Neha', 'neha@gmail.com', '2024-03-01')
])

conn.commit()
cursor.executemany("""
INSERT INTO Orders VALUES (?, ?, ?, ?)
""", [
    (1001, 1, '2024-05-01', 15500.00),
    (1002, 2, '2024-05-02', 55000.00),
    (1003, 3, '2024-05-03', 700.00)
])

conn.commit()
pd.read_sql("""
SELECT p.ProductName, c.CategoryName, p.Price
FROM Products p
JOIN Categories c
ON p.CategoryID = c.CategoryID;
""", conn)
pd.read_sql("""
SELECT o.OrderID, c.CustomerName, o.OrderDate, o.TotalAmount
FROM Orders o
JOIN Customers c
ON o.CustomerID = c.CustomerID;
""", conn)

   OrderID CustomerName   OrderDate  TotalAmount
0     1001        Ruchi  2024-05-01        15500
1     1002         Amit  2024-05-02        55000
2     1003         Neha  2024-05-03          700

In [19]:
import sqlite3
import pandas as pd

# Connect database
conn = sqlite3.connect('ECommerceDB.db')
cursor = conn.cursor()

# Enable foreign keys
cursor.execute("PRAGMA foreign_keys = ON;")

# Drop tables if already exist
cursor.executescript("""
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Products;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Categories;
""")

# Create tables
cursor.executescript("""
CREATE TABLE Categories (
    CategoryID INT PRIMARY KEY,
    CategoryName VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Products (
    ProductID INT PRIMARY KEY,
    ProductName VARCHAR(100) NOT NULL UNIQUE,
    CategoryID INT,
    Price DECIMAL(10,2) NOT NULL,
    StockQuantity INT,
    FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID)
);

CREATE TABLE Customers (
    CustomerID INT PRIMARY KEY,
    CustomerName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE,
    JoinDate DATE
);

CREATE TABLE Orders (
    OrderID INT PRIMARY KEY,
    CustomerID INT,
    OrderDate DATE NOT NULL,
    TotalAmount DECIMAL(10,2),
    FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
);
""")

# Insert data
cursor.executescript("""
INSERT INTO Categories VALUES
(1,'Electronics'),(2,'Books'),(3,'Home Goods'),(4,'Apparel');

INSERT INTO Products VALUES
(101,'Laptop Pro',1,1200.00,50),
(102,'SQL Handbook',2,45.50,200),
(103,'Smart Speaker',1,99.99,150),
(104,'Coffee Maker',3,75.00,80),
(105,'Novel : The Great SQL',2,25.00,120),
(106,'Wireless Earbuds',1,150.00,100),
(107,'Blender X',3,120.00,60),
(108,'T-Shirt Casual',4,20.00,300);

INSERT INTO Customers VALUES
(1,'Alice Wonderland','alice@example.com','2023-01-10'),
(2,'Bob the Builder','bob@example.com','2022-11-25'),
(3,'Charlie Chaplin','charlie@example.com','2023-03-01'),
(4,'Diana Prince','diana@example.com','2021-04-26');

INSERT INTO Orders VALUES
(1001,1,'2023-04-26',1245.50),
(1002,2,'2023-10-12',99.99),
(1003,1,'2023-07-01',145.00),
(1004,3,'2023-01-14',150.00),
(1005,2,'2023-09-24',120.00),
(1006,1,'2023-06-19',20.00);
""")

conn.commit()

# Show tables output
print("Categories Table:")
display(pd.read_sql("SELECT * FROM Categories;", conn))

print("Products Table:")
display(pd.read_sql("SELECT * FROM Products;", conn))

print("Customers Table:")
display(pd.read_sql("SELECT * FROM Customers;", conn))

print("Orders Table:")
display(pd.read_sql("SELECT * FROM Orders;", conn))

Categories Table:

   CategoryID CategoryName
0           1  Electronics
1           2        Books
2           3   Home Goods
3           4      Apparel

Products Table:

   ProductID            ProductName  CategoryID    Price  StockQuantity
0        101             Laptop Pro           1  1200.00             50
1        102           SQL Handbook           2    45.50            200
2        103          Smart Speaker           1    99.99            150
3        104           Coffee Maker           3    75.00             80
4        105  Novel : The Great SQL           2    25.00            120
5        106       Wireless Earbuds           1   150.00            100
6        107              Blender X           3   120.00             60
7        108         T-Shirt Casual           4    20.00            300

Customers Table:

   CustomerID      CustomerName                Email    JoinDate
0           1  Alice Wonderland    alice@example.com  2023-01-10
1           2   Bob the Builder      bob@example.com  2022-11-25
2           3   Charlie Chaplin  charlie@example.com  2023-03-01
3           4      Diana Prince    diana@example.com  2021-04-26

Orders Table:

   OrderID  CustomerID   OrderDate  TotalAmount
0     1001           1  2023-04-26      1245.50
1     1002           2  2023-10-12        99.99
2     1003           1  2023-07-01       145.00
3     1004           3  2023-01-14       150.00
4     1005           2  2023-09-24       120.00
5     1006           1  2023-06-19        20.00

Question 7 : Generate a report showing CustomerName, Email, and the TotalNumberofOrders for each customer. Include customers who have not placed any orders.

In [ ]:
query = """
SELECT
    c.CustomerName,
    c.Email,
    COUNT(o.OrderID) AS TotalNumberofOrders
FROM Customers c
LEFT JOIN Orders o ON c.CustomerID = o.CustomerID
GROUP BY c.CustomerID, c.CustomerName, c.Email
ORDER BY c.CustomerName;
"""

pd.read_sql(query, conn)

Question 8 : Retrieve Product Information with Category.

In [20]:
query = """
SELECT
    p.ProductName,
    p.Price,
    p.StockQuantity,
    c.CategoryName
FROM Products p
JOIN Categories c ON p.CategoryID = c.CategoryID
ORDER BY c.CategoryName, p.ProductName;
"""

pd.read_sql(query, conn)

             ProductName    Price  StockQuantity CategoryName
0         T-Shirt Casual    20.00            300      Apparel
1  Novel : The Great SQL    25.00            120        Books
2           SQL Handbook    45.50            200        Books
3             Laptop Pro  1200.00             50  Electronics
4          Smart Speaker    99.99            150  Electronics
5       Wireless Earbuds   150.00            100  Electronics
6              Blender X   120.00             60   Home Goods
7           Coffee Maker    75.00             80   Home Goods

Question 9 : Write a SQL query that uses a Common Table Expression (CTE) and a Window Function to display the top 2 most expensive products in each CategoryName.

In [22]:
query = """
WITH RankedProducts AS (
    SELECT
        c.CategoryName,
        p.ProductName,
        p.Price,
        ROW_NUMBER() OVER(PARTITION BY c.CategoryName ORDER BY p.Price DESC) AS rn
    FROM Products p
    JOIN Categories c ON p.CategoryID = c.CategoryID
)
SELECT CategoryName, ProductName, Price
FROM RankedProducts
WHERE rn <= 2;
"""

pd.read_sql(query, conn)

  CategoryName            ProductName   Price
0      Apparel         T-Shirt Casual    20.0
1        Books           SQL Handbook    45.5
2        Books  Novel : The Great SQL    25.0
3  Electronics             Laptop Pro  1200.0
4  Electronics       Wireless Earbuds   150.0
5   Home Goods              Blender X   120.0
6   Home Goods           Coffee Maker    75.0

Question 10 : Sakila Database Business Analysis Queries

In [27]:
# Install sql magic
!pip install ipython-sql sqlalchemy prettytable

# Load SQL magic
%load_ext sql

# Connect to SQLite database
%sql sqlite:///sakila.db

# 1. Top 5 customers by spending
%%sql
SELECT
    c.first_name || ' ' || c.last_name AS CustomerName,
    c.email,
    SUM(p.amount) AS TotalSpent
FROM customer c
JOIN payment p ON c.customer_id = p.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name, c.email
ORDER BY TotalSpent DESC
LIMIT 5;


# 2. Top 3 movie categories by rentals
%%sql
SELECT
    cat.name AS CategoryName,
    COUNT(*) AS RentalCount
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film_category fc ON i.film_id = fc.film_id
JOIN category cat ON fc.category_id = cat.category_id
GROUP BY cat.name
ORDER BY RentalCount DESC
LIMIT 3;


# 3. Films available and never rented per store
%%sql
SELECT
    s.store_id,
    COUNT(i.inventory_id) AS TotalFilms,
    SUM(CASE WHEN r.rental_id IS NULL THEN 1 ELSE 0 END) AS NeverRented
FROM store s
JOIN inventory i ON s.store_id = i.store_id
LEFT JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY s.store_id;


# 4. Monthly revenue for 2023
%%sql
SELECT
    strftime('%m', payment_date) AS Month,
    SUM(amount) AS TotalRevenue
FROM payment
WHERE strftime('%Y', payment_date) = '2023'
GROUP BY Month
ORDER BY Month;


# 5. Customers rented more than 10 times in last 6 months
%%sql
SELECT
    c.customer_id,
    c.first_name || ' ' || c.last_name AS CustomerName,
    COUNT(r.rental_id) AS RentalCount
FROM customer c
JOIN rental r ON c.customer_id = r.customer_id
WHERE r.rental_date >= date('now','-6 months')
GROUP BY c.customer_id, c.first_name, c.last_name
HAVING COUNT(r.rental_id) > 10;

IndentationError: unexpected indent (ipython-input-1747979293.py, line 13)